In [1]:
# data processing
import numpy as np
import pandas as pd

# data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# statistics
from scipy import stats
from scipy.stats import chi2_contingency

# others
from google.colab import drive
import io
import os
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', 500)

In [2]:
df = pd.read_csv("/content/sample_data/loan_data_2007_2014.csv")
df.head()

,,,,,,,,,,,,,,0,Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717,Borrower added on 12/04/13 > My loan is to relieve monthly stress of high interest payments so I can finish my home improvements to allow more room for my family.<br>,debt_consolidation,Debt consolidation,898xx,NV,19.17,0.0,Aug-02,1.0,46.0,Unnamed: 16,9.0,0.0.1,5543,50.4,30.0,w,0.0.2,0.0.3,10801.93,10801.93.1,10000.0,801.93,0.0.4,0.0.5,0.0.6,Feb-15,6734.1,Unnamed: 34,Jan-16,0.0.7,46.0.1,1,INDIVIDUAL,Unnamed: 40,Unnamed: 41,Unnamed: 42,0.0.8,0.0.9,323663.0,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,11000.0,Unnamed: 58,Unnamed: 59,Unnamed: 60
52732,9434687,11266834,7000,7000,7000.0,36 months,11.99,232.47,B,B3,Parent Service Cord.,10+ years,MORTGAGE,55000.00,Not Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Credit card consolidation,212xx,MD,4.32,1.0,Dec-00,0.0,23.0,NaN,9.0,0.0,4437,39.3,38.0,f,0.00,0.00,8062.526210,8062.53,7000.00,1062.53,0.0,0.0,0.0,Jul-15,3878.15,NaN,Sep-15,0.0,23.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,4437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11300.0,NaN,NaN,NaN
52733,9394809,11226937,13000,13000,13000.0,36 months,13.53,441.35,B,B5,NaN,NaN,OWN,40275.24,Verified,Dec-13,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,951xx,CA,2.73,1.0,Aug-76,1.0,11.0,NaN,4.0,0.0,1854,61.8,12.0,w,4541.75,4541.75,11033.750000,11033.75,8458.25,2575.50,0.0,0.0,0.0,Jan-16,441.35,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,2372.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,NaN,NaN,NaN
52734,9484732,11316866,2500,2500,2500.0,36 months,10.99,81.84,B,B2,Installer,7 years,RENT,30720.00,Not Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,credit card payoff,850xx,AZ,10.31,0.0,Oct-07,2.0,NaN,NaN,7.0,0.0,2944,64.0,10.0,w,0.00,0.00,2545.260000,2545.26,2500.00,45.26,0.0,0.0,0.0,Feb-14,2463.42,NaN,Feb-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,14554.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4600.0,NaN,NaN,NaN
52735,9484701,11316838,15000,15000,15000.0,60 months,18.25,382.95,D,D3,OFFICE MANAGER,10+ years,RENT,77000.00,Source Verified,Dec-13,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > to pay off cred...,debt_consolidation,DEBT CONSOLIDATION,902xx,CA,18.66,0.0,Jun-98,0.0,NaN,NaN,14.0,0.0,23321,84.8,24.0,f,10333.46,10333.46,9573.290000,9573.29,4666.54,4906.75,0.0,0.0,0.0,Jan-16,382.95,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,31241.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27500.0,NaN,NaN,NaN
52736,9484577,11316726,8400,8400,8400.0,36 months,14.47,289.02,C,C2,instructor,3 years,MORTGAGE,109765.00,Source Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > PAYOFF CREDIT C...,debt_consolidation,Debt consolidation,770xx,TX,24.53,0.0,Mar-99,0.0,NaN,NaN,9.0,0.0,10417,72.8,15.0,w,0.00,0.00,9227.781517,9227.78,8400.00,827.78,0.0,0.0,0.0,Sep-14,6915.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,107826.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14300.0,NaN,NaN,NaN

In [3]:
df.shape

(413553, 61)

# **DATA UNDERSTANDING**

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 413553 entries, (np.int64(52732), np.int64(9434687), np.int64(11266834), np.int64(7000), np.int64(7000), np.float64(7000.0), ' 36 months', np.float64(11.99), np.float64(232.47), 'B', 'B3', 'Parent Service Cord.', '10+ years', 'MORTGAGE') to (np.int64(466284), np.int64(9199665), np.int64(11061576), np.int64(10000), np.int64(10000), np.float64(9975.0), ' 36 months', np.float64(19.2), np.float64(367.58), 'D', 'D3', nan, '10+ years', 'MORTGAGE')
Data columns (total 61 columns):
 #   Column                                                                                                                                                                    Non-Null Count   Dtype
---  ------                                                                                                                                                                    --------------   -----
 0   0                                                                                                                                                                         413553 non-null  float64
 1   Verified                                                                                                                                                                  413553 non-null  object
 2   Dec-13                                                                                                                                                                    413553 non-null  object
 3   Fully Paid                                                                                                                                                                413553 non-null  object
 4   n                                                                                                                                                                         413553 non-null  object
 5   https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717                                                                                                      413553 non-null  object
 6     Borrower added on 12/04/13 > My loan is to relieve monthly stress of high interest payments so I can finish my home improvements to allow more room for my family.<br>  93382 non-null   object
 7   debt_consolidation                                                                                                                                                        413553 non-null  object
 8   Debt consolidation                                                                                                                                                        413545 non-null  object
 9   898xx                                                                                                                                                                     413553 non-null  object
 10  NV                                                                                                                                                                        413553 non-null  object
 11  19.17                                                                                                                                                                     413553 non-null  float64
 12  0.0                                                                                                                                                                       413553 non-null  float64
 13  Aug-02                                                                                                                                                                    413553 non-null  object
 14  1.0                                                                                                                                                                       413553 non-null  float64
 15  46.0                                                                                                                                                                      195478 non-null  float64
 16  Unnamed: 16                                                                                                                                                               57592 non-null   float64
 17  9.0                                                                                                                                                                       413553 non-null  float64
 18  0.0.1                                                                                                                                                                     413553 non-null  float64
 19  5543                                                                                                                                                                      413553 non-null  int64
 20  50.4                                                                                                                                                                      413309 non-null  float64
 21  30.0                                                                                                                                                                      413553 non-null  float64
 22  w                                                                                                                                                                         413553 non-null  object
 23  0.0.2                                                                                                                                                                     413553 non-null  float64
 24  0.0.3                                                                                                                                                                     413553 non-null  float64
 25  10801.93                                                                                                                                                                  413553 non-null  float64
 26  10801.93.1                                                                                                                                                                413553 non-null  float64
 27  10000.0                                                                                                                                                                   413553 non-null  float64
 28  801.93                                                                                                                                                                    413553 non-null  float64
 29  0.0.4                                                                                                                                                                     413553 non-null  float64
 30  0.0.5                                                                                                                                                                     413553 non-null  float64
 31  0.0.6                                                                                                                                                                     413553 non-null  float64
 32  Feb-15                                                                                                                                                                    413265 non-null  object
 33  6734.1                                                                                                                                                                    413553 non-null  float64
 34  Unnamed: 34                                                                                                                                                               228596 non-null  object
 35  Jan-16                                                                                                                                                                    413515 non-null  object
 36  0.0.7                                                                                                                                                                     413553 non-null  float64
 37  46.0.1                                                                                                                                                                    96620 non-null   float64
 38  1                                                                                                                                                                         413553 non-null  int64
 39  INDIVIDUAL                                                                                                                                                                413553 non-null  object
 40  Unnamed: 40                                                                                                                                                               0 non-null       float64
 41  Unnamed: 41                                                                                                                                                               0 non-null       float64
 42  Unnamed: 42                                                                                                                                                               0 non-null       float64
 43  0.0.8                                                                                                                                                                     413553 non-null  float64
 44  0.0.9                                                                                                                                                                     385812 non-null  float64
 45  323663.0                                                                                                                                                                  385812 non-null  float64
 46  Unnamed: 46                                                                                                                                                               0 non-null       float64
 47  Unnamed: 47                                                                                                                                                               0 non-null       float64
 48  Unnamed: 48                                                                                                                                                               0 non-null       float64
 49  Unnamed: 49                                                                                                                                                               0 non-null       float64
 50  Unnamed: 50                                                                                                                                                               0 non-null       float64
 51  Unnamed: 51                                                                                                                                                               0 non-null       float64
 52  Unnamed: 52                                                                                                                                                               0 non-null       float64
 53  Unnamed: 53                                                                                                                                                               0 non-null       float64
 54  Unnamed: 54                                                                                                                                                               0 non-null       float64
 55  Unnamed: 55                                                                                                                                                               0 non-null       float64
 56  Unnamed: 56                                                                                                                                                               0 non-null       float64
 57  11000.0                                                                                                                                                                   385812 non-null  float64
 58  Unnamed: 58                                                                                                                                                               0 non-null       float64
 59  Unnamed: 59                                                                                                                                                               0 non-null       float64
 60  Unnamed: 60                                                                                                                                                               0 non-null       float64
dtypes: float64(43), int64(2), object(16)
memory usage: 270.3+ MB

In [5]:
df

,,,,,,,,,,,,,,0,Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717,Borrower added on 12/04/13 > My loan is to relieve monthly stress of high interest payments so I can finish my home improvements to allow more room for my family.<br>,debt_consolidation,Debt consolidation,898xx,NV,19.17,0.0,Aug-02,1.0,46.0,Unnamed: 16,9.0,0.0.1,5543,50.4,30.0,w,0.0.2,0.0.3,10801.93,10801.93.1,10000.0,801.93,0.0.4,0.0.5,0.0.6,Feb-15,6734.1,Unnamed: 34,Jan-16,0.0.7,46.0.1,1,INDIVIDUAL,Unnamed: 40,Unnamed: 41,Unnamed: 42,0.0.8,0.0.9,323663.0,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,11000.0,Unnamed: 58,Unnamed: 59,Unnamed: 60
52732,9434687,11266834,7000,7000,7000.0,36 months,11.99,232.47,B,B3,Parent Service Cord.,10+ years,MORTGAGE,55000.00,Not Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Credit card consolidation,212xx,MD,4.32,1.0,Dec-00,0.0,23.0,NaN,9.0,0.0,4437,39.3,38.0,f,0.00,0.00,8062.526210,8062.53,7000.00,1062.53,0.0,0.0,0.0,Jul-15,3878.15,NaN,Sep-15,0.0,23.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,4437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11300.0,NaN,NaN,NaN
52733,9394809,11226937,13000,13000,13000.0,36 months,13.53,441.35,B,B5,NaN,NaN,OWN,40275.24,Verified,Dec-13,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,951xx,CA,2.73,1.0,Aug-76,1.0,11.0,NaN,4.0,0.0,1854,61.8,12.0,w,4541.75,4541.75,11033.750000,11033.75,8458.25,2575.50,0.0,0.0,0.0,Jan-16,441.35,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,2372.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,NaN,NaN,NaN
52734,9484732,11316866,2500,2500,2500.0,36 months,10.99,81.84,B,B2,Installer,7 years,RENT,30720.00,Not Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,credit card payoff,850xx,AZ,10.31,0.0,Oct-07,2.0,NaN,NaN,7.0,0.0,2944,64.0,10.0,w,0.00,0.00,2545.260000,2545.26,2500.00,45.26,0.0,0.0,0.0,Feb-14,2463.42,NaN,Feb-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,14554.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4600.0,NaN,NaN,NaN
52735,9484701,11316838,15000,15000,15000.0,60 months,18.25,382.95,D,D3,OFFICE MANAGER,10+ years,RENT,77000.00,Source Verified,Dec-13,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > to pay off cred...,debt_consolidation,DEBT CONSOLIDATION,902xx,CA,18.66,0.0,Jun-98,0.0,NaN,NaN,14.0,0.0,23321,84.8,24.0,f,10333.46,10333.46,9573.290000,9573.29,4666.54,4906.75,0.0,0.0,0.0,Jan-16,382.95,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,31241.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27500.0,NaN,NaN,NaN
52736,9484577,11316726,8400,8400,8400.0,36 months,14.47,289.02,C,C2,instructor,3 years,MORTGAGE,109765.00,Source Verified,Dec-13,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > PAYOFF CREDIT C...,debt_consolidation,Debt consolidation,770xx,TX,24.53,0.0,Mar-99,0.0,NaN,NaN,9.0,0.0,10417,72.8,15.0,w,0.00,0.00,9227.781517,9227.78,8400.00,827.78,0.0,0.0,0.0,Sep-14,6915.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,107826.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14300.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.00,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.0,0.0,0.0,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.00,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.0,0.0,0.0,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.00,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.0,0.0,0.0,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.00,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.0,0.0,0.0,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.00,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.0,0.0,0.0,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [6]:
# DataFrame untuk menyimpan kolom dan tipe data
df_type = pd.DataFrame({'Columns':df.columns, 'Type':df.dtypes.values})
# Kelompokkan berdasarkan tipe data
df_type = df_type.sort_values(by="Type").reset_index(drop=True)
df_type.index = df_type.index + 1 # Start from 1 index

from tabulate import tabulate
print(tabulate(df_type,headers="keys",tablefmt="grid"))

+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|    | Columns                                                                                                                                                                | Type    |
+====+========================================================================================================================================================================+=========+
|  1 | 1                                                                                                                                                                      | int64   |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  2 | 5543                                                                                                                                                                   | int64   |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  3 | 0                                                                                                                                                                      | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  4 | 0.0.6                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  5 | 6734.1                                                                                                                                                                 | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  6 | 0.0.7                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  7 | 46.0.1                                                                                                                                                                 | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  8 | Unnamed: 40                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  9 | Unnamed: 41                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 10 | Unnamed: 42                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 11 | 0.0.8                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 12 | 0.0.9                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 13 | 323663.0                                                                                                                                                               | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 14 | Unnamed: 46                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 15 | Unnamed: 47                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 16 | Unnamed: 48                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 17 | Unnamed: 49                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 18 | Unnamed: 50                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 19 | Unnamed: 51                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 20 | Unnamed: 52                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 21 | Unnamed: 53                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 22 | Unnamed: 54                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 23 | Unnamed: 55                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 24 | Unnamed: 56                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 25 | 11000.0                                                                                                                                                                | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 26 | Unnamed: 58                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 27 | Unnamed: 59                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 28 | 0.0.4                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 29 | 0.0.5                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 30 | 10000.0                                                                                                                                                                | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 31 | 19.17                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 32 | 0.0                                                                                                                                                                    | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 33 | 1.0                                                                                                                                                                    | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 34 | 801.93                                                                                                                                                                 | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 35 | Unnamed: 16                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 36 | 9.0                                                                                                                                                                    | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 37 | 0.0.1                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 38 | 50.4                                                                                                                                                                   | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 39 | 46.0                                                                                                                                                                   | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 40 | Unnamed: 60                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 41 | 0.0.2                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 42 | 0.0.3                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 43 | 10801.93                                                                                                                                                               | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 44 | 10801.93.1                                                                                                                                                             | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 45 | 30.0                                                                                                                                                                   | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 46 | Verified                                                                                                                                                               | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 47 | Dec-13                                                                                                                                                                 | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 48 | Fully Paid                                                                                                                                                             | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 49 | n                                                                                                                                                                      | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 50 | https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717                                                                                                   | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 51 | Borrower added on 12/04/13 > My loan is to relieve monthly stress of high interest payments so I can finish my home improvements to allow more room for my family.<br> | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 52 | debt_consolidation                                                                                                                                                     | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+

In [7]:
df.columns

Index(['0', 'Verified', 'Dec-13', 'Fully Paid', 'n',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717',
       '  Borrower added on 12/04/13 > My loan is to relieve monthly stress of high interest payments so I can finish my home improvements to allow more room for my family.<br>',
       'debt_consolidation', 'Debt consolidation', '898xx', 'NV', '19.17',
       '0.0', 'Aug-02', '1.0', '46.0', 'Unnamed: 16', '9.0', '0.0.1', '5543',
       '50.4', '30.0', 'w', '0.0.2', '0.0.3', '10801.93', '10801.93.1',
       '10000.0', '801.93', '0.0.4', '0.0.5', '0.0.6', 'Feb-15', '6734.1',
       'Unnamed: 34', 'Jan-16', '0.0.7', '46.0.1', '1', 'INDIVIDUAL',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', '0.0.8', '0.0.9',
       '323663.0', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53',
       'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', '11000.0', 'Unnamed: 58',
       'Unnamed: 59', 'Unnamed: 60'],
      dtype='object')

In [8]:
df['Fully Paid'].unique()

array(['Fully Paid', 'Current', 'In Grace Period', 'Charged Off',
       'Late (31-120 days)', 'Default', 'Late (16-30 days)'], dtype=object)

In [9]:
df['good_bad']=np.where(df.loc[:,'Fully Paid'].isin(['Charged off','Default','Late(31-120 days)']), 1, 0)

In [10]:
df.good_bad.value_counts()

good_bad
0    412747
1       806
Name: count, dtype: int64

In [11]:
df[['Fully Paid','good_bad']]

,,,,,,,,,,,,,,Fully Paid,good_bad
52732,9434687,11266834,7000,7000,7000.0,36 months,11.99,232.47,B,B3,Parent Service Cord.,10+ years,MORTGAGE,Fully Paid,0
52733,9394809,11226937,13000,13000,13000.0,36 months,13.53,441.35,B,B5,NaN,NaN,OWN,Current,0
52734,9484732,11316866,2500,2500,2500.0,36 months,10.99,81.84,B,B2,Installer,7 years,RENT,Fully Paid,0
52735,9484701,11316838,15000,15000,15000.0,60 months,18.25,382.95,D,D3,OFFICE MANAGER,10+ years,RENT,Current,0
52736,9484577,11316726,8400,8400,8400.0,36 months,14.47,289.02,C,C2,instructor,3 years,MORTGAGE,Fully Paid,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,Current,0
466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,Charged Off,0
466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,Current,0
466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,Fully Paid,0
466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,Current,0

In [12]:
df[df.duplicated()]

Empty DataFrame
Columns: [0, Verified, Dec-13, Fully Paid, n, https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717,   Borrower added on 12/04/13 > My loan is to relieve monthly stress of high interest payments so I can finish my home improvements to allow more room for my family.<br>, debt_consolidation, Debt consolidation, 898xx, NV, 19.17, 0.0, Aug-02, 1.0, 46.0, Unnamed: 16, 9.0, 0.0.1, 5543, 50.4, 30.0, w, 0.0.2, 0.0.3, 10801.93, 10801.93.1, 10000.0, 801.93, 0.0.4, 0.0.5, 0.0.6, Feb-15, 6734.1, Unnamed: 34, Jan-16, 0.0.7, 46.0.1, 1, INDIVIDUAL, Unnamed: 40, Unnamed: 41, Unnamed: 42, 0.0.8, 0.0.9, 323663.0, Unnamed: 46, Unnamed: 47, Unnamed: 48, Unnamed: 49, Unnamed: 50, Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, 11000.0, Unnamed: 58, Unnamed: 59, Unnamed: 60, good_bad]
Index: []

In [13]:
# DataFrame untuk menyimpan kolom dan tipe data
df_type = pd.DataFrame({'Columns':df.columns, 'Type':df.dtypes.values})
# Kelompokkan berdasarkan tipe data
df_type = df_type.sort_values(by="Type").reset_index(drop=True)
df_type.index = df_type.index + 1 # Start from 1 index

from tabulate import tabulate
print(tabulate(df_type,headers="keys",tablefmt="grid"))

+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|    | Columns                                                                                                                                                                | Type    |
+====+========================================================================================================================================================================+=========+
|  1 | good_bad                                                                                                                                                               | int64   |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  2 | 1                                                                                                                                                                      | int64   |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  3 | 5543                                                                                                                                                                   | int64   |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  4 | 0.0.6                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  5 | 6734.1                                                                                                                                                                 | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  6 | 0.0.7                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  7 | 46.0.1                                                                                                                                                                 | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  8 | Unnamed: 40                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
|  9 | Unnamed: 41                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 10 | Unnamed: 42                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 11 | 0.0.8                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 12 | 0.0.9                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 13 | 323663.0                                                                                                                                                               | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 14 | Unnamed: 60                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 15 | Unnamed: 46                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 16 | Unnamed: 48                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 17 | Unnamed: 49                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 18 | Unnamed: 50                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 19 | Unnamed: 51                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 20 | Unnamed: 52                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 21 | Unnamed: 53                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 22 | Unnamed: 54                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 23 | Unnamed: 55                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 24 | Unnamed: 56                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 25 | 11000.0                                                                                                                                                                | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 26 | Unnamed: 58                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 27 | Unnamed: 59                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 28 | Unnamed: 47                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 29 | 0.0.4                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 30 | 0                                                                                                                                                                      | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 31 | 10000.0                                                                                                                                                                | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 32 | 19.17                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 33 | 0.0                                                                                                                                                                    | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 34 | 1.0                                                                                                                                                                    | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 35 | 801.93                                                                                                                                                                 | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 36 | Unnamed: 16                                                                                                                                                            | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 37 | 9.0                                                                                                                                                                    | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 38 | 0.0.1                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 39 | 50.4                                                                                                                                                                   | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 40 | 30.0                                                                                                                                                                   | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 41 | 46.0                                                                                                                                                                   | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 42 | 0.0.5                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 43 | 0.0.2                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 44 | 0.0.3                                                                                                                                                                  | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 45 | 10801.93                                                                                                                                                               | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 46 | 10801.93.1                                                                                                                                                             | float64 |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 47 | Verified                                                                                                                                                               | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 48 | Dec-13                                                                                                                                                                 | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 49 | Fully Paid                                                                                                                                                             | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 50 | n                                                                                                                                                                      | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 51 | https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717                                                                                                   | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 52 | Borrower added on 12/04/13 > My loan is to relieve monthly stress of high interest payments so I can finish my home improvements to allow more room for my family.<br> | object  |
+----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+

# EXPLORATORY DATA ANALYSIS (EDA)

**Handling** **Missing** **Value**

In [14]:
missing_values= pd.DataFrame(df.isnull().sum()/df.shape[0])
display(missing_values)

                   0
0            0.00000
Verified     0.00000
Dec-13       0.00000
Fully Paid   0.00000
n            0.00000
...              ...
11000.0      0.06708
Unnamed: 58  1.00000
Unnamed: 59  1.00000
Unnamed: 60  1.00000
good_bad     0.00000

[62 rows x 1 columns]

In [15]:
missing_values=missing_values[missing_values.iloc[:,0]>0.50]

In [16]:
missing_values.sort_values([0], ascending=False)

                                                           0
Unnamed: 40                                         1.000000
Unnamed: 47                                         1.000000
Unnamed: 46                                         1.000000
Unnamed: 42                                         1.000000
Unnamed: 41                                         1.000000
Unnamed: 52                                         1.000000
Unnamed: 53                                         1.000000
Unnamed: 54                                         1.000000
Unnamed: 55                                         1.000000
Unnamed: 48                                         1.000000
Unnamed: 49                                         1.000000
Unnamed: 50                                         1.000000
Unnamed: 51                                         1.000000
Unnamed: 56                                         1.000000
Unnamed: 58                                         1.000000
Unnamed: 59                                         1.000000
Unnamed: 60                                         1.000000
Unnamed: 16                                         0.860739
  Borrower added on 12/04/13 > My loan is to re...  0.774196
46.0.1                                              0.766366
46.0                                                0.527321

In [17]:
df.dropna(thresh=df.shape[0]*0.5, axis=1, inplace=True)

In [18]:
missing_values= pd.DataFrame(df.isnull().sum()/df.shape[0])
display(missing_values)
missing_values= pd.DataFrame(df.isnull().sum()/df.shape[0])
display(missing_values)
missing_values.sort_values([0], ascending=False)

                                                           0
0                                                   0.000000
Verified                                            0.000000
Dec-13                                              0.000000
Fully Paid                                          0.000000
n                                                   0.000000
https://www.lendingclub.com/browse/loanDetail.a...  0.000000
debt_consolidation                                  0.000000
Debt consolidation                                  0.000019
898xx                                               0.000000
NV                                                  0.000000
19.17                                               0.000000
0.0                                                 0.000000
Aug-02                                              0.000000
1.0                                                 0.000000
9.0                                                 0.000000
0.0.1                                               0.000000
5543                                                0.000000
50.4                                                0.000590
30.0                                                0.000000
w                                                   0.000000
0.0.2                                               0.000000
0.0.3                                               0.000000
10801.93                                            0.000000
10801.93.1                                          0.000000
10000.0                                             0.000000
801.93                                              0.000000
0.0.4                                               0.000000
0.0.5                                               0.000000
0.0.6                                               0.000000
Feb-15                                              0.000696
6734.1                                              0.000000
Unnamed: 34                                         0.447239
Jan-16                                              0.000092
0.0.7                                               0.000000
1                                                   0.000000
INDIVIDUAL                                          0.000000
0.0.8                                               0.000000
0.0.9                                               0.067080
323663.0                                            0.067080
11000.0                                             0.067080
good_bad                                            0.000000

                                                           0
0                                                   0.000000
Verified                                            0.000000
Dec-13                                              0.000000
Fully Paid                                          0.000000
n                                                   0.000000
https://www.lendingclub.com/browse/loanDetail.a...  0.000000
debt_consolidation                                  0.000000
Debt consolidation                                  0.000019
898xx                                               0.000000
NV                                                  0.000000
19.17                                               0.000000
0.0                                                 0.000000
Aug-02                                              0.000000
1.0                                                 0.000000
9.0                                                 0.000000
0.0.1                                               0.000000
5543                                                0.000000
50.4                                                0.000590
30.0                                                0.000000
w                                                   0.000000
0.0.2                                               0.000000
0.0.3                                               0.000000
10801.93                                            0.000000
10801.93.1                                          0.000000
10000.0                                             0.000000
801.93                                              0.000000
0.0.4                                               0.000000
0.0.5                                               0.000000
0.0.6                                               0.000000
Feb-15                                              0.000696
6734.1                                              0.000000
Unnamed: 34                                         0.447239
Jan-16                                              0.000092
0.0.7                                               0.000000
1                                                   0.000000
INDIVIDUAL                                          0.000000
0.0.8                                               0.000000
0.0.9                                               0.067080
323663.0                                            0.067080
11000.0                                             0.067080
good_bad                                            0.000000

                                                           0
Unnamed: 34                                         0.447239
11000.0                                             0.067080
0.0.9                                               0.067080
323663.0                                            0.067080
Feb-15                                              0.000696
50.4                                                0.000590
Jan-16                                              0.000092
Debt consolidation                                  0.000019
0                                                   0.000000
898xx                                               0.000000
debt_consolidation                                  0.000000
https://www.lendingclub.com/browse/loanDetail.a...  0.000000
n                                                   0.000000
Dec-13                                              0.000000
Fully Paid                                          0.000000
Verified                                            0.000000
NV                                                  0.000000
5543                                                0.000000
30.0                                                0.000000
0.0                                                 0.000000
19.17                                               0.000000
1.0                                                 0.000000
9.0                                                 0.000000
0.0.1                                               0.000000
Aug-02                                              0.000000
10000.0                                             0.000000
10801.93.1                                          0.000000
10801.93                                            0.000000
0.0.3                                               0.000000
0.0.2                                               0.000000
w                                                   0.000000
0.0.6                                               0.000000
801.93                                              0.000000
6734.1                                              0.000000
0.0.4                                               0.000000
0.0.5                                               0.000000
0.0.7                                               0.000000
0.0.8                                               0.000000
INDIVIDUAL                                          0.000000
1                                                   0.000000
good_bad                                            0.000000

**Data** **Splitting**

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
# Membagi data menjadi 80/20 dengan menyamakan distribusi dari bad loans di test set dengan train set.
X = df.drop('good_bad', axis=1)
y = df['good_bad']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, stratify= y, random_state=42)

In [21]:
y_train.value_counts(normalize=True)

good_bad
0    0.99805
1    0.00195
Name: proportion, dtype: float64

In [22]:
# Distribusi y_test sudah sama persis dengan y_train
y_test.value_counts(normalize=True)

good_bad
0    0.998053
1    0.001947
Name: proportion, dtype: float64

# **DATA CLEANING**

In [23]:
X_train.shape

(330842, 40)

In [24]:
#Dapat dilakukan print untuk semua unique values kolom, sehingga dapat di cek satu-satu
# unique values apa saja yang kotor.

for col in X_train.select_dtypes(include= ['object','bool']).columns:
    print(col)
    print(X_train[col].unique())
    print()

Verified
['Verified' 'Source Verified' 'Not Verified']

Dec-13
['Apr-13' 'Feb-14' 'May-13' 'Sep-14' 'Aug-13' 'Oct-14' 'Apr-14' 'May-14'
 'Oct-13' 'Jan-14' 'Nov-12' 'Nov-14' 'Sep-13' 'Mar-13' 'Nov-13' 'Jun-13'
 'Jul-13' 'Mar-14' 'Sep-12' 'Aug-12' 'Jul-14' 'Dec-12' 'Aug-14' 'Feb-12'
 'May-12' 'Jun-14' 'Dec-14' 'Apr-12' 'Jan-13' 'Feb-13' 'Jan-12' 'Oct-12'
 'Dec-13' 'Jun-12' 'Jul-12' 'Mar-12']

Fully Paid
['Current' 'Charged Off' 'Fully Paid' 'Late (31-120 days)' 'Default'
 'In Grace Period' 'Late (16-30 days)']

n
['n' 'y']

https://www.lendingclub.com/browse/loanDetail.action?loan_id=9414717
['https://www.lendingclub.com/browse/loanDetail.action?loan_id=4194948'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=11687286'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=5444875'
 ...
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=22231573'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=5038375'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=16181584']

debt_consolidation
['debt_consolidation' 'credit_card' 'car' 'home_improvement'
 'small_business' 'medical' 'other' 'vacation' 'house' 'major_purchase'
 'renewable_energy' 'moving' 'wedding']

Debt consolidation
['Debt consolidation' 'payoff' 'bill consolidation' ...
 'Build my credit  ' 'Small business loan' 'Operation Debt Clean Up']

898xx
['913xx' '751xx' '200xx' '029xx' '919xx' '787xx' '347xx' '100xx' '261xx'
 '921xx' '070xx' '935xx' '982xx' '940xx' '133xx' '371xx' '112xx' '207xx'
 '356xx' '554xx' '028xx' '953xx' '911xx' '010xx' '857xx' '309xx' '301xx'
 '981xx' '452xx' '933xx' '760xx' '804xx' '641xx' '530xx' '891xx' '926xx'
 '271xx' '037xx' '076xx' '215xx' '233xx' '532xx' '762xx' '959xx' '850xx'
 '990xx' '063xx' '336xx' '972xx' '956xx' '800xx' '280xx' '480xx' '240xx'
 '925xx' '606xx' '282xx' '236xx' '337xx' '189xx' '296xx' '795xx' '114xx'
 '945xx' '073xx' '605xx' '905xx' '941xx' '928xx' '286xx' '142xx' '210xx'
 '806xx' '660xx' '024xx' '841xx' '331xx' '297xx' '852xx' '664xx' '908xx'
 '704xx' '750xx' '115xx' '558xx' '922xx' '318xx' '350xx' '217xx' '237xx'
 '880xx' '216xx' '330xx' '441xx' '134xx' '460xx' '712xx' '993xx' '018xx'
 '553xx' '796xx' '937xx' '871xx' '300xx' '957xx' '776xx' '080xx' '254xx'
 '752xx' '761xx' '360xx' '483xx' '329xx' '088xx' '131xx' '810xx' '146xx'
 '917xx' '706xx' '206xx' '770xx' '729xx' '161xx' '977xx' '199xx' '380xx'
 '923xx' '290xx' '802xx' '713xx' '395xx' '900xx' '358xx' '324xx' '111xx'
 '774xx' '303xx' '996xx' '902xx' '950xx' '968xx' '140xx' '816xx' '870xx'
 '232xx' '967xx' '971xx' '117xx' '652xx' '413xx' '191xx' '673xx' '104xx'
 '294xx' '450xx' '274xx' '481xx' '156xx' '797xx' '720xx' '890xx' '648xx'
 '562xx' '785xx' '328xx' '019xx' '851xx' '379xx' '494xx' '531xx' '551xx'
 '103xx' '325xx' '278xx' '021xx' '980xx' '556xx' '910xx' '983xx' '085xx'
 '211xx' '105xx' '714xx' '775xx' '612xx' '767xx' '799xx' '437xx' '976xx'
 '633xx' '144xx' '119xx' '123xx' '446xx' '829xx' '259xx' '404xx' '801xx'
 '310xx' '640xx' '118xx' '344xx' '317xx' '113xx' '782xx' '165xx' '661xx'
 '986xx' '078xx' '456xx' '373xx' '740xx' '600xx' '468xx' '853xx' '788xx'
 '209xx' '915xx' '920xx' '765xx' '306xx' '436xx' '773xx' '907xx' '557xx'
 '334xx' '847xx' '547xx' '228xx' '448xx' '655xx' '672xx' '458xx' '666xx'
 '220xx' '177xx' '338xx' '234xx' '087xx' '668xx' '863xx' '615xx' '208xx'
 '173xx' '479xx' '463xx' '731xx' '068xx' '069xx' '949xx' '898xx' '201xx'
 '214xx' '627xx' '809xx' '016xx' '859xx' '705xx' '346xx' '656xx' '026xx'
 '637xx' '231xx' '342xx' '339xx' '498xx' '359xx' '367xx' '440xx' '060xx'
 '958xx' '305xx' '176xx' '276xx' '805xx' '435xx' '196xx' '072xx' '495xx'
 '442xx' '130xx' '601xx' '815xx' '288xx' '082xx' '064xx' '952xx' '153xx'
 '970xx' '270xx' '066xx' '856xx' '454xx' '151xx' '302xx' '447xx' '975xx'
 '431xx' '275xx' '882xx' '050xx' '723xx' '150xx' '667xx' '321xx' '768xx'
 '674xx' '152xx' '264xx' '803xx' '563xx' '405xx' '927xx' '813xx' '293xx'
 '930xx' '061xx' '283xx' '484xx' '462xx' '951xx' '250xx' '707xx' '221xx'
 '700xx' '109xx' '482xx' '622xx' '820xx' '351xx' '735xx' '071xx' '381xx'
 '675xx' '461xx' '322xx' '906xx' '701xx' '985xx' '077xx' '757xx' '645xx'
 '106xx' '786xx' '222xx' '159xx' '748xx' '597xx' '287xx' '721xx' '128xx'
 '604xx' '136xx' '840xx' '465xx' '081xx' '180xx' '125xx' '473xx' '190xx'
 '067xx' '015xx' '265xx' '132xx' '559xx' '432xx' '535xx' '944xx' '780xx'
 '012xx' '594xx' '989xx' '291xx' '079xx' '285xx' '946xx' '631xx' '444xx'
 '090xx' '490xx' '370xx' '766xx' '333xx' '550xx' '145xx' '074xx' '110xx'
 '174xx' '241xx' '054xx' '754xx' '327xx' '383xx' '747xx' '245xx' '121xx'
 '320xx' '603xx' '939xx' '281xx' '427xx' '451xx' '299xx' '120xx' '430xx'
 '932xx' '402xx' '730xx' '877xx' '736xx' '194xx' '931xx' '195xx' '741xx'
 '326xx' '030xx' '138xx' '571xx' '017xx' '488xx' '973xx' '262xx' '995xx'
 '992xx' '354xx' '469xx' '279xx' '934xx' '561xx' '476xx' '991xx' '391xx'
 '759xx' '335xx' '129xx' '781xx' '107xx' '229xx' '453xx' '226xx' '726xx'
 '038xx' '630xx' '307xx' '219xx' '549xx' '365xx' '611xx' '614xx' '182xx'
 '790xx' '961xx' '560xx' '124xx' '127xx' '027xx' '954xx' '486xx' '492xx'
 '292xx' '390xx' '591xx' '984xx' '936xx' '020xx' '053xx' '065xx' '014xx'
 '960xx' '361xx' '860xx' '011xx' '794xx' '083xx' '743xx' '793xx' '593xx'
 '746xx' '948xx' '023xx' '141xx' '284xx' '904xx' '062xx' '864xx' '570xx'
 '025xx' '223xx' '295xx' '894xx' '257xx' '764xx' '157xx' '708xx' '662xx'
 '179xx' '822xx' '357xx' '544xx' '543xx' '537xx' '086xx' '449xx' '160xx'
 '362xx' '332xx' '598xx' '620xx' '467xx' '471xx' '487xx' '135xx' '457xx'
 '665xx' '193xx' '417xx' '389xx' '548xx' '828xx' '974xx' '540xx' '075xx'
 '566xx' '565xx' '924xx' '496xx' '830xx' '170xx' '826xx' '651xx' '185xx'
 '341xx' '235xx' '654xx' '172xx' '474xx' '811xx' '783xx' '798xx' '916xx'
 '255xx' '955xx' '895xx' '392xx' '198xx' '304xx' '267xx' '443xx' '272xx'
 '678xx' '035xx' '238xx' '903xx' '403xx' '410xx' '147xx' '212xx' '716xx'
 '493xx' '273xx' '376xx' '372xx' '778xx' '988xx' '485xx' '912xx' '445xx'
 '947xx' '725xx' '616xx' '363xx' '618xx' '719xx' '164xx' '225xx' '638xx'
 '171xx' '855xx' '253xx' '352xx' '573xx' '607xx' '032xx' '166xx' '914xx'
 '224xx' '610xx' '401xx' '058xx' '997xx' '148xx' '644xx' '423xx' '756xx'
 '368xx' '218xx' '378xx' '258xx' '814xx' '034xx' '409xx' '181xx' '478xx'
 '184xx' '116xx' '609xx' '247xx' '033xx' '242xx' '175xx' '711xx' '613xx'
 '031xx' '197xx' '497xx' '308xx' '400xx' '734xx' '657xx' '628xx' '599xx'
 '168xx' '470xx' '108xx' '539xx' '727xx' '546xx' '386xx' '545xx' '366xx'
 '489xx' '377xx' '411xx' '323xx' '703xx' '710xx' '635xx' '455xx' '248xx'
 '738xx' '677xx' '089xx' '178xx' '102xx' '137xx' '812xx' '881xx' '312xx'
 '875xx' '183xx' '439xx' '722xx' '843xx' '013xx' '052xx' '789xx' '791xx'
 '277xx' '844xx' '385xx' '824xx' '918xx' '472xx' '883xx' '464xx' '639xx'
 '230xx' '186xx' '355xx' '943xx' '397xx' '394xx' '420xx' '658xx' '384xx'
 '349xx' '596xx' '246xx' '629xx' '422xx' '421xx' '084xx' '625xx' '670xx'
 '827xx' '056xx' '739xx' '623xx' '227xx' '057xx' '433xx' '122xx' '617xx'
 '669xx' '466xx' '602xx' '671xx' '978xx' '244xx' '763xx' '298xx' '634xx'
 '825xx' '724xx' '755xx' '836xx' '313xx' '434xx' '749xx' '396xx' '717xx'
 '846xx' '315xx' '251xx' '163xx' '577xx' '319xx' '382xx' '608xx' '792xx'
 '263xx' '808xx' '541xx' '187xx' '745xx' '243xx' '865xx' '169xx' '564xx'
 '807xx' '316xx' '626xx' '188xx' '364xx' '784xx' '155xx' '491xx' '998xx'
 '737xx' '260xx' '314xx' '249xx' '407xx' '154xx' '158xx' '647xx' '845xx'
 '239xx' '646xx' '374xx' '424xx' '051xx' '425xx' '718xx' '636xx' '653xx'
 '475xx' '575xx' '592xx' '415xx' '874xx' '897xx' '162xx' '650xx' '758xx'
 '873xx' '567xx' '728xx' '777xx' '744xx' '252xx' '388xx' '769xx' '268xx'
 '049xx' '101xx' '139xx' '412xx' '022xx' '572xx' '538xx' '542xx' '595xx'
 '590xx' '256xx' '398xx' '679xx' '126xx' '406xx' '477xx' '574xx' '779xx'
 '393xx' '289xx' '893xx' '624xx' '438xx' '534xx' '879xx' '416xx' '834xx'
 '418xx' '167xx' '408xx' '823xx' '821xx' '969xx' '994xx' '676xx' '619xx'
 '979xx' '884xx' '426xx' '143xx' '499xx' '772xx' '266xx' '753xx' '999xx'
 '878xx' '311xx' '094xx' '096xx' '149xx' '831xx' '092xx' '414xx' '387xx'
 '621xx' '369xx' '098xx' '036xx' '963xx' '059xx' '576xx' '523xx' '008xx'
 '680xx' '043xx' '962xx' '093xx' '091xx' '942xx' '527xx' '938xx' '682xx'
 '044xx' '587xx' '007xx' '340xx' '513xx' '888xx' '582xx' '832xx' '643xx'
 '901xx' '854xx' '429xx' '685xx' '502xx' '500xx' '510xx' '833xx' '889xx'
 '524xx' '681xx' '353xx']

NV
['CA' 'TX' 'DC' 'RI' 'FL' 'NY' 'WV' 'NJ' 'WA' 'TN' 'MD' 'AL' 'MN' 'MA'
 'AZ' 'GA' 'OH' 'CO' 'MO' 'WI' 'NV' 'NC' 'NH' 'VA' 'CT' 'OR' 'MI' 'IL'
 'PA' 'SC' 'KS' 'UT' 'LA' 'NM' 'IN' 'AR' 'DE' 'MS' 'AK' 'HI' 'KY' 'WY'
 'OK' 'VT' 'MT' 'SD' 'ID' 'NE' 'ME' 'IA']

Aug-02
['Aug-07' 'Jul-02' 'Sep-69' 'Feb-98' 'Oct-98' 'Mar-90' 'Nov-92' 'Mar-88'
 'Oct-01' 'Nov-05' 'Nov-03' 'Nov-00' 'May-98' 'Apr-90' 'Nov-95' 'May-97'
 'Mar-04' 'Sep-78' 'Aug-89' 'Dec-72' 'Apr-02' 'Jun-00' 'Jan-10' 'Nov-97'
 'Oct-89' 'Oct-00' 'Aug-04' 'Aug-99' 'Jan-92' 'Feb-99' 'Oct-95' 'Jan-91'
 'May-93' 'Jun-94' 'Aug-98' 'May-96' 'Dec-01' 'Jan-01' 'Oct-96' 'Apr-99'
 'Nov-02' 'May-99' 'Jul-76' 'Jul-04' 'Dec-90' 'Sep-95' 'May-85' 'Mar-96'
 'Jul-96' 'Jul-89' 'Nov-99' 'Jan-03' 'Nov-96' 'Aug-05' 'Mar-95' 'Nov-89'
 'Dec-98' 'Nov-06' 'Jan-04' 'Nov-93' 'Dec-84' 'Jul-88' 'Sep-01' 'Jan-07'
 'Jul-00' 'Jun-99' 'Jun-88' 'Sep-00' 'Oct-92' 'Dec-77' 'Jun-04' 'Jul-01'
 'May-02' 'Jan-00' 'Sep-91' 'May-01' 'Sep-03' 'Jul-86' 'Aug-01' 'Oct-94'
 'Sep-84' 'May-73' 'Jan-99' 'Apr-07' 'Jul-90' 'Jan-96' 'Apr-98' 'Jun-02'
 'Jun-78' 'Nov-84' 'Nov-88' 'Jun-92' 'Oct-08' 'Jun-82' 'Dec-02' 'Jul-03'
 'Sep-98' 'Aug-02' 'Jun-03' 'Mar-02' 'Jun-98' 'May-95' 'Dec-00' 'Mar-03'
 'Jan-97' 'Dec-92' 'Aug-03' 'Aug-00' 'Oct-05' 'Nov-94' 'Jun-97' 'May-03'
 'Sep-96' 'Mar-99' 'Sep-05' 'May-05' 'Aug-97' 'Aug-96' 'May-04' 'Sep-04'
 'Jan-79' 'Apr-95' 'Jan-95' 'Apr-79' 'Feb-89' 'Nov-04' 'May-87' 'Sep-94'
 'Dec-04' 'Apr-91' 'Nov-01' 'Apr-89' 'Aug-88' 'Sep-89' 'Dec-96' 'Dec-97'
 'Aug-95' 'Oct-04' 'Aug-87' 'Feb-90' 'Apr-03' 'Oct-93' 'Apr-00' 'Feb-93'
 'Jan-05' 'Mar-00' 'Feb-94' 'Oct-97' 'Mar-01' 'Aug-86' 'Oct-99' 'Feb-85'
 'Mar-98' 'Sep-99' 'Oct-83' 'Apr-05' 'Apr-01' 'Feb-97' 'Mar-89' 'May-92'
 'Jul-05' 'Jan-93' 'Sep-02' 'Jul-99' 'Feb-96' 'Jul-97' 'Nov-98' 'Jun-06'
 'Mar-83' 'Aug-93' 'Mar-92' 'Apr-78' 'Feb-00' 'Jan-06' 'Jun-96' 'Sep-85'
 'May-91' 'May-84' 'Jun-95' 'May-10' 'Feb-01' 'Feb-08' 'Feb-87' 'Feb-03'
 'May-89' 'Oct-06' 'Jul-91' 'Mar-05' 'Aug-75' 'Sep-93' 'Jan-89' 'May-94'
 'Feb-91' 'Jun-87' 'Mar-06' 'Feb-95' 'Sep-97' 'Aug-94' 'Jun-83' 'May-00'
 'Jul-94' 'Apr-93' 'Aug-09' 'Aug-06' 'Mar-93' 'Apr-96' 'Jan-02' 'Jun-01'
 'Jul-06' 'Feb-67' 'Jun-07' 'Nov-90' 'Mar-82' 'Dec-87' 'Jun-05' 'Sep-06'
 'Jun-89' 'Sep-76' 'Feb-02' 'Aug-08' 'Feb-79' 'Sep-87' 'Aug-92' 'Sep-08'
 'Oct-87' 'Aug-11' 'Jun-90' 'Oct-84' 'Nov-80' 'Sep-90' 'Feb-07' 'Apr-83'
 'Jan-94' 'Jul-79' 'Sep-80' 'Oct-85' 'Dec-99' 'Jun-84' 'Feb-74' 'May-86'
 'Apr-06' 'Oct-02' 'Dec-03' 'Apr-94' 'Jul-95' 'Apr-97' 'Nov-85' 'Jan-88'
 'Aug-91' 'Jul-07' 'Mar-78' 'Jun-91' 'Mar-86' 'May-06' 'Feb-88' 'May-88'
 'Feb-04' 'Jan-98' 'Dec-81' 'Dec-06' 'Dec-93' 'Oct-81' 'Jan-70' 'Sep-72'
 'Dec-95' 'Jul-98' 'Aug-84' 'Aug-90' 'Nov-08' 'Feb-92' 'Sep-92' 'Aug-10'
 'Dec-91' 'Apr-92' 'Mar-97' 'Mar-94' 'Mar-81' 'Mar-09' 'Aug-80' 'Jul-93'
 'Dec-86' 'Apr-86' 'Jun-72' 'Dec-88' 'Nov-07' 'Aug-85' 'Jul-85' 'Nov-82'
 'Jul-92' 'May-07' 'Jun-93' 'Dec-07' 'Feb-05' 'Oct-03' 'Oct-90' 'Feb-78'
 'Jun-81' 'Dec-89' 'Dec-85' 'Mar-73' 'Sep-07' 'Jan-86' 'May-90' 'Mar-84'
 'Jul-82' 'Feb-06' 'Apr-65' 'Jan-90' 'Apr-68' 'Mar-80' 'Sep-10' 'Mar-77'
 'Mar-85' 'Dec-05' 'May-08' 'Feb-77' 'Apr-87' 'Jun-67' 'May-09' 'Sep-74'
 'Jan-83' 'Aug-83' 'Aug-81' 'Jan-65' 'Mar-91' 'Sep-82' 'Dec-08' 'Nov-74'
 'Aug-77' 'Jan-87' 'Apr-04' 'Jan-09' 'Feb-11' 'Mar-08' 'Oct-91' 'May-11'
 'Sep-88' 'Dec-94' 'Jan-74' 'Feb-09' 'Sep-65' 'Nov-87' 'Aug-67' 'Apr-08'
 'Jul-87' 'Jul-78' 'Nov-79' 'Dec-09' 'Jul-83' 'Mar-07' 'Jul-08' 'Feb-86'
 'Mar-79' 'Nov-83' 'Mar-87' 'Apr-77' 'Jul-10' 'Apr-75' 'Jun-08' 'Nov-73'
 'Oct-78' 'Apr-85' 'May-79' 'Jan-80' 'Jan-08' 'Nov-86' 'Oct-09' 'Mar-72'
 'Apr-66' 'Feb-84' 'Apr-10' 'Nov-81' 'Oct-07' 'Sep-86' 'Nov-69' 'May-83'
 'Jul-75' 'Oct-88' 'Apr-88' 'Sep-09' 'Mar-11' 'Nov-75' 'Jan-75' 'May-77'
 'Jun-76' 'Jun-86' 'Dec-10' 'Oct-86' 'Jul-09' 'Sep-75' 'Sep-83' 'Jun-62'
 'Jul-80' 'Aug-82' 'Nov-91' 'Apr-09' 'May-78' 'Jan-84' 'Aug-69' 'Sep-77'
 'May-76' 'Feb-83' 'Jun-80' 'Dec-82' 'Nov-11' 'Jan-85' 'Aug-74' 'Oct-72'
 'Apr-82' 'Dec-71' 'Aug-78' 'Nov-78' 'Sep-67' 'Apr-81' 'Mar-10' 'Oct-80'
 'Jan-69' 'Dec-74' 'Feb-75' 'Mar-75' 'Sep-79' 'Nov-77' 'May-80' 'Dec-76'
 'Nov-71' 'Sep-81' 'Jul-84' 'Apr-61' 'Aug-76' 'Apr-84' 'Dec-79' 'Jan-81'
 'Jan-11' 'Jun-79' 'Jan-67' 'Nov-72' 'Jul-81' 'Sep-71' 'Jun-77' 'Aug-79'
 'Mar-70' 'Oct-82' 'Nov-09' 'Aug-63' 'Oct-79' 'Dec-69' 'Dec-80' 'Oct-73'
 'Apr-11' 'Jun-10' 'Jun-85' 'Feb-80' 'Jun-09' 'Jan-73' 'Jun-71' 'Feb-81'
 'Jan-82' 'May-59' 'Jan-76' 'Dec-75' 'Feb-82' 'Jan-77' 'Aug-71' 'Nov-10'
 'Jan-54' 'Dec-73' 'Oct-74' 'Feb-70' 'Mar-76' 'Jun-68' 'Oct-75' 'Sep-64'
 'Jan-68' 'May-81' 'Apr-70' 'Feb-73' 'Dec-68' 'Apr-76' 'Feb-10' 'Nov-68'
 'Oct-10' 'Apr-69' 'May-69' 'Sep-68' 'May-75' 'Jun-11' 'Jul-71' 'May-82'
 'Jun-66' 'Jul-68' 'Dec-70' 'Sep-73' 'Apr-73' 'Aug-72' 'May-68' 'Jan-66'
 'Sep-11' 'Oct-77' 'Jul-73' 'May-72' 'Dec-78' 'Jul-69' 'Oct-70' 'Apr-80'
 'Nov-54' 'Mar-63' 'Mar-69' 'May-74' 'Dec-64' 'Jun-70' 'Oct-67' 'Apr-72'
 'Dec-51' 'Oct-69' 'Jul-11' 'Jun-74' 'Dec-83' 'Jul-63' 'Feb-69' 'Nov-76'
 'Feb-76' 'Jul-77' 'Nov-67' 'Feb-71' 'Jan-78' 'Jan-72' 'Oct-76' 'Jan-63'
 'Apr-71' 'Jul-74' 'Feb-72' 'Jul-65' 'Jun-73' 'Aug-73' 'Sep-66' 'Nov-70'
 'Oct-71' 'Mar-74' 'Jul-70' 'Nov-64' 'Jun-75' 'May-71' 'May-66' 'Oct-65'
 'May-70' 'Oct-66' 'Oct-11' 'Mar-68' 'Dec-67' 'Feb-68' 'Nov-65' 'Mar-59'
 'May-67' 'Jan-60' 'Apr-74' 'Jan-71' 'Oct-59' 'Apr-63' 'Jul-72' 'Aug-68'
 'Dec-66' 'Aug-60' 'Jun-69' 'Feb-61' 'Feb-65' 'May-64' 'Apr-67' 'Jan-61'
 'Apr-64' 'Jul-66' 'Dec-63' 'Oct-60' 'Nov-62' 'Mar-62' 'Sep-70' 'Jul-67'
 'Nov-63' 'Aug-65' 'Mar-67' 'Dec-65' 'Jun-63' 'Aug-66' 'Dec-60' 'Jul-59'
 'Aug-64' 'Nov-66' 'Mar-71' 'Jan-62' 'Mar-66' 'Oct-68' 'Aug-70' 'Sep-57'
 'Jul-60' 'Oct-63' 'Oct-64' 'Apr-55' 'Oct-62' 'May-58' 'Sep-60' 'Jun-61'
 'Jul-64' 'Dec-62' 'Jun-65' 'Jan-57' 'Jan-64' 'Jun-60' 'Mar-65' 'Jan-58'
 'Jan-59' 'Jan-55' 'Jun-64' 'Mar-64' 'Nov-60' 'Sep-62' 'Dec-56' 'Feb-66'
 'Nov-59' 'Mar-61' 'Aug-62' 'Nov-53' 'Jan-51' 'Sep-63' 'Oct-58' 'May-63'
 'Nov-50' 'Nov-58' 'Jun-58' 'Nov-56' 'May-62' 'Sep-59' 'Nov-55' 'May-65'
 'Feb-63' 'Oct-61' 'Aug-61' 'Dec-58' 'Jul-62' 'Jan-44' 'Jan-53' 'Feb-64'
 'May-50' 'Feb-57' 'Jul-61' 'Nov-61' 'Mar-60' 'May-60' 'Apr-62' 'Jul-55'
 'Jun-59' 'Jan-56' 'Feb-60' 'Aug-58']

w
['w' 'f']

Feb-15
['Jan-16' 'Dec-15' 'May-15' 'Mar-14' 'May-14' 'Jan-15' 'Mar-15' 'Aug-14'
 'Jul-15' 'Sep-15' 'Nov-15' 'Feb-15' 'Sep-14' 'Oct-13' 'Jun-15' 'Jul-14'
 'Sep-13' 'Apr-13' 'Oct-15' 'Apr-15' 'Oct-14' 'Dec-13' 'Jun-14' 'Nov-14'
 'Aug-15' 'Jun-13' 'Apr-14' 'Jan-14' 'Nov-13' 'Oct-12' 'Feb-14' 'Aug-13'
 'Aug-12' 'Feb-13' 'Dec-14' 'Jul-13' 'May-13' 'Jun-12' 'Mar-13' 'Nov-12'
 'Jan-13' nan 'Dec-12' 'Jul-12' 'Sep-12' 'Apr-12' 'May-12' 'Mar-12'
 'Feb-12']

Unnamed: 34
['Feb-16' 'Jan-16' nan 'Mar-16']

Jan-16
['Jan-16' 'Dec-15' 'Apr-14' 'Jun-15' 'Mar-15' 'Feb-15' 'Apr-15' 'Sep-14'
 'Nov-14' 'Jan-15' 'May-15' 'Sep-13' 'Nov-15' 'Jul-15' 'May-14' 'Dec-14'
 'Oct-14' 'Jun-14' 'Aug-15' 'Dec-13' 'Sep-15' 'Jul-14' 'Nov-13' 'Oct-15'
 'Aug-13' 'Aug-14' 'Mar-13' 'Mar-14' 'Oct-13' 'Jun-12' 'Feb-14' 'Jan-14'
 'Feb-13' 'Jun-13' 'Apr-13' 'Aug-12' 'May-13' 'Dec-12' 'Jul-13' 'Oct-12'
 'Jul-12' 'May-12' 'Nov-12' 'Mar-12' 'Sep-12' nan 'Feb-12' 'Jan-13'
 'Jan-12' 'Apr-12']

INDIVIDUAL
['INDIVIDUAL']

In [25]:
# Kolom/feature yang harus di cleaning
col_need_to_clean = ['term', 'emp_length', 'issue_d', 'earliest_cr_line', 'last_pymnt_d',
                    'next_pymnt_d', 'last_credit_pull_d']

In [27]:
# Menghilangkan ' months' menjadi ''
X_train['term'].str.replace('months', '')

KeyError: 'term'

In [29]:
# Cek values apa saja yang harus di cleaning
X_train[' emp_length'].unique()

KeyError: ' emp_length'

In [30]:
# Cek feature date
col_date = ['issue_d', 'earliest_cr_line', 'last_pymnt_d',
                    'next_pymnt_d', 'last_credit_pull_d']

X_train[col_date]

KeyError: "None of [Index(['issue_d', 'earliest_cr_line', 'last_pymnt_d', 'next_pymnt_d',\n       'last_credit_pull_d'],\n      dtype='object')] are in the [columns]"

In [31]:
df_imputed.isnull().sum()

NameError: name 'df_imputed' is not defined